version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      - POSTGRES_DB=countries
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - mka_pgdata:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  mka_pgdata:
