server:
  port: 8080

spring:
  application:
    name: countries-api
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/countries
    username: postgres
    password: postgres
  servlet:
    multipart:
      enabled: true


logging:
  level:
    com.demis27.countries: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
